/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as hypercertMinterUpgradeSol from "./HypercertMinterUpgrade.sol";

export type { hypercertMinterUpgradeSol };
export type { ERC3525_Testing } from "./ERC3525_Testing";
