# This is a basic workflow to help you get started with Actions

name: CI - Testing

# env:
#   INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
#   MNEMONIC: ${{ secrets.MNEMONIC }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    # The type of runner that the job will run on
    name: Build and test The Graph
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"
        working-directory: ./graph

      - name: Code-gen
        run: yarn codegen
        working-directory: ./graph

      - name: Test
        run: yarn test
        working-directory: ./graph